---

- name: Need xauth for our final target
  yum:
    name: xauth
    state: latest
    validate_certs: no
  become: yes

- name: Need xclock on our final target
  yum:
    name: xclock
    state: latest
    validate_certs: no
  become: yes

- name: Overwrite the sshd_config
  copy:
    backup: yes
    src: 'files/sshd_config'
    dest: '/etc/ssh/sshd_config'
  register: sshd_changes
  become: yes

- service:
    name: sshd
    state: restarted
  become: yes
